
when:
  - event: tag
#    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  build_and_publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "index.docker.io,quay.io/"
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      logins:
        - registry: "https://index.docker.io/v1/"
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password

        - registry: "https://quay.io"
          username:
            from_secret: quay_username
          password:
            from_secret: quay_password
