variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:latest'
  - &publish_repos 'opencloudeu/wccs,quay.io/opencloudeu/wccs'
  - &publish_platforms 'linux/arm64,linux/amd64'
  - publish_logins: &publish_logins
      - registry: https://index.docker.io/v1/
        username:
          from_secret: docker_username
        password:
          from_secret: docker_password
      - registry: https://quay.io
        username:
          from_secret: quay_username
        password:
          from_secret: quay_password

when:
  - event: [tag]
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  publish:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile
      platforms: *publish_platforms
      tag: [ '${CI_COMMIT_TAG%%.*}', '${CI_COMMIT_TAG%.*}', '${CI_COMMIT_TAG}', 'latest' ]
      logins: *publish_logins
    when:
      event: tag
