variables:
  - &golang_image 'docker.io/golang:1.24'
  - &when
    - path: &when_path
        - '.woodpecker/test.yaml'
        - '**/*.go'
        - 'go.*'
      event: pull_request

when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path: *when_path

steps:
  
  vendor:
    image: *golang_image
    commands:
      - go mod vendor
    when:
      path:
        - <<: *when_path
        - '.woodpecker/**'

  lint:
    depends_on:
      - vendor
    image: *golang_image
    commands:
      - make lint
    when: *when

  test:
    depends_on:
      - vendor
    image: *golang_image
    commands:
      - make test
    when:
      - path: *when_path
